version: '3.9'

networks:
  net-traefik:
    external: true

services:

  # loki:
  #   image: grafana/loki:latest
  #   ports:
  #     - 3100:3100/tcp
  #   volumes:
  #     - ./loki-config.yaml:/etc/loki/local-config.yaml
  #   command: -config.file=/etc/loki/local-config.yaml


  prometheus:
     image: prom/prometheus:latest
     container_name: prometheus
     restart: unless-stopped
     command:
       - --web.enable-remote-write-receiver
       - --config.file=/etc/prometheus/prometheus.yml
     ports:
       - 9090:9090/tcp
     labels:
       - homepage.group=Grafana Prometheus Alloy
       - homepage.name=Prometheus
       - homepage.icon=prometheus.svg
       - homepage.description=Prometheus Data
     volumes:
        - ${PROMETHEUS_CONFIG_PATH}:/etc/prometheus/prometheus.yml
        - gpa-prometheus-data:/prometheus
        - /etc/localtime:/etc/localtime:ro


  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    networks: 
       - net-traefik
       - default
    labels:
      - traefik.enable=true
      
      - traefik.http.routers.grafana-https.rule=Host(`${SERVICE_NAME_URL}.${DOMAIN_NAME}`)
      - traefik.http.routers.grafana-https.entrypoints=websecure
      - traefik.http.routers.grafana-https.tls=true

      - traefik.http.routers.grafana-redir.rule=Host(`${SERVICE_NAME_URL}`)
      - traefik.http.routers.grafana-redir.entrypoints=web
      - traefik.http.routers.grafana-redir.middlewares=mgeneralredir

      - traefik.http.routers.grafana-redir-https.rule=Host(`${SERVICE_NAME_URL}`)
      - traefik.http.routers.grafana-redir-https.entrypoints=websecure
      - traefik.http.routers.grafana-redir-https.middlewares=mgeneralredir
      - traefik.http.routers.grafana-redir-https.tls=true
            
      - traefik.http.routers.grafana-http.entrypoints=web
      - traefik.http.routers.grafana-http.rule=Host(`${SERVICE_NAME_URL}.${DOMAIN_NAME}`)
      - traefik.http.routers.grafana-http.middlewares=redirect-to-https
      - traefik.docker.network=net-traefik

      - homepage.group=Grafana Prometheus Alloy
      - homepage.name=Grafana
      - homepage.icon=grafana.svg
      - homepage.description=Grafana Dashboard

    ports:
      - 3999:3000/tcp
    volumes:
      - gpa-grafana-data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
       - sh
       - -euc
       - |
         mkdir -p /etc/grafana/provisioning/datasources
         cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
         apiVersion: 1
         datasources:
         - name: Loki
           type: loki
           access: proxy
           orgId: 1
           url: http://loki:3100
           basicAuth: false
           isDefault: false
           version: 1
           editable: false
         - name: Prometheus
           type: prometheus
           orgId: 1
           url: http://prometheus:9090
           basicAuth: false
           isDefault: true
           version: 1
           editable: false
         EOF
         /run.sh

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: nuc13
    privileged: true

    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.03'
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - --stability.level=experimental
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gpa-alloy-data:/var/lib/alloy/data
      - ${ALLOY_CONFIG_PATH}:/etc/alloy/config.alloy
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    labels: 
      - homepage.group=Grafana Prometheus Alloy
      - homepage.name=Alloy
      - homepage.icon=alloy.svg
      - homepage.description=Alloy Scrapper


volumes:
  gpa-grafana-data:
    external: true
  gpa-prometheus-data:
    external: true
  gpa-alloy-data:
    external: true