version: '3'
services:
    adguardhome:
        image: adguard/adguardhome:latest
        container_name: adguardhome
        restart: unless-stopped
        networks:
            - net-traefik
        labels:
            - traefik.enable=true
            
            - traefik.http.routers.adguard-redir.rule=Host(`${SERVICE_NAME_URL}`)
            - traefik.http.routers.adguard-redir.entrypoints=web
            - traefik.http.routers.adguard-redir.middlewares=mgeneralredir

            - traefik.http.routers.adguard-redir-https.rule=Host(`${SERVICE_NAME_URL}`)
            - traefik.http.routers.adguard-redir-https.entrypoints=websecure
            - traefik.http.routers.adguard-redir-https.middlewares=mgeneralredir
            - traefik.http.routers.adguard-redir-https.tls=true
            
            - traefik.http.routers.adguard.entrypoints=web
            - traefik.http.routers.adguard.rule=Host(`${SERVICE_NAME_URL}.${DOMAIN_NAME}`)
            - traefik.http.routers.adguard.middlewares=redirect-to-https
            
            - traefik.http.routers.adguard-https.entrypoints=websecure
            - traefik.http.routers.adguard-https.rule=Host(`${SERVICE_NAME_URL}.${DOMAIN_NAME}`)
            - traefik.http.services.adguard-https.loadbalancer.server.port=80
            - traefik.http.routers.adguard-https.tls=true

        ports:
            # Expose port 53 on TCP and UDP for DNS queries
            - "53:53/tcp"
            - "53:53/udp"

            # Expose port 67 on UDP for DHCP server
            #- "67:67/udp"

            # Expose port 68 on UDP for DHCP client
            # - "68:68/udp"

            # Expose port 80 on TCP for HTTP web interface
            - "8089:80/tcp"

            # Expose port 443 on TCP and UDP for HTTPS web interface
            #- "443:443/tcp"
            #- "443:443/udp"

            # Expose port 3000 on TCP for AdGuard Home's API
            - "3000:3000/tcp"

            # Expose port 853 on TCP for DNS-over-TLS (DoT)
            #- "853:853/tcp"

            # Expose port 784 on UDP for DNS-over-QUIC (DoQ)
            #- "784:784/udp"

            # Expose port 853 on UDP for DNS-over-DTLS (DoT)
            #- "853:853/udp"

            # Expose port 8853 on UDP for DNS-over-TLS (DoT)
            #- "8853:8853/udp"

            # Expose port 5443 on TCP and UDP for DNSCrypt
            #- "5443:5443/tcp"
            #- "5443:5443/udp"
            
        volumes:  # Mount host directories as volumes inside the container
            - adguard-work:/opt/adguardhome/work  # Mount '/my/own/workdir' to '/opt/adguardhome/work'
            - adguard-conf:/opt/adguardhome/conf  # Mount '/my/own/confdir' to '/opt/adguardhome/conf'
volumes:
    adguard-work:
        external: true
    adguard-conf:
        external: true
networks:
    net-traefik:
        external: true
