version: "3"
services:
  cloudflaretunnel:
    container_name: cloudflaretunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    networks:
      - net-cloudflare
    #network_mode: host

networks:
  net-cloudflare:
    external: true