services:
    postgres16:
        image: linhares/postgres16-homelab:1.0.0
        container_name: postgres16
        restart: unless-stopped
        networks: 
          - net-db
        env_file:
          - .env
        volumes:
          - postgres16:/var/lib/postgresql/data
          - /etc/localtime:/etc/localtime:ro

volumes:
  postgres16:
    external: true

networks:
  net-db:
    external: true